---

- name: Ensure Database locales
  locale_gen: name={{ limesurvey_db_lc_ctype }} state=present
  notify: restart postgresql

- name: Create LimeSurvey Database
  become: yes
  become_user: postgres
  postgresql_db: name={{ limesurvey_db_name }}
                 encoding={{ limesurvey_db_encoding }}
                 template={{ limesurvey_db_template }}
  notify: restart postgresql

- name: Add LimeSurvey Database User
  become: yes
  become_user: postgres
  postgresql_user: db={{ limesurvey_db_name }}
                   name={{ limesurvey_user }}
  notify: restart postgresql

- name: Ensure LimeSurvey Database Privileges
  become: yes
  become_user: postgres
  postgresql_privs: db={{ limesurvey_db_name }}
                    role={{ limesurvey_user }}
                    privs=ALL
                    type=database
                    grant_option=yes
  notify: restart postgresql

- name: Get location of pg_hba.conf
  command: "psql -t -P format=unaligned -c 'show hba_file';"
  register: pg_hba_cmd
  become: yes
  become_user: postgres

- name: Host based authentication
  become: yes
  become_user: postgres
  blockinfile:
    dest: "{{ pg_hba_cmd.stdout }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    insertafter: "# User custom"
    block: |
      host {{ limesurvey_db_name }} {{ limesurvey_user }} 127.0.0.1/32 trust
  notify: restart postgresql
